### Bibliotecas Importadas

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

### Matriz A

In [1]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])


print(A.shape)

(3, 2)


### Descomposición SVD de una Matriz

In [3]:
U, S, VT = np.linalg.svd(A)
print(f"Matriz U: {U}")
print(f"Matriz Sigma: {S}")
print(f"Matriz VT: {VT}")

Matriz U: [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Matriz Sigma: [9.52551809 0.51430058]
Matriz VT: [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


### Creación de Matriz Diagonal de Sigma

In [8]:
diagonal_S = np.diag(S)
print(f"Matriz diagonal de Sigma: {diagonal_S}")


filas_ceros=np.zeros((1,2))
print(f"Filas de ceros: {filas_ceros}")

Sigma = np.concatenate((diagonal_S, filas_ceros), axis=0)
print(f"Matriz Sigma con ceros añadidos: {Sigma}")

Matriz diagonal de Sigma: [[9.52551809 0.        ]
 [0.         0.51430058]]
Filas de ceros: [[0. 0.]]
Matriz Sigma con ceros añadidos: [[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]


### Reconstrucción de la Matriz A a partir de U, Sigma y VT

In [10]:
print(f"Matriz U: {U}")
print(f"Matriz Sigma: {Sigma}")
print(f"Matriz VT: {VT}")

A_reconstruida = U @ Sigma @ VT
print(f"Matriz A reconstruida: {A_reconstruida}")

Matriz U: [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Matriz Sigma: [[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]
Matriz VT: [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
Matriz A reconstruida: [[1. 2.]
 [3. 4.]
 [5. 6.]]
