### Filtrar Ruido con SVD en un Sistema de Recomendación

In [3]:
import numpy as np

#### Patrones de Scifi y Comedia

In [4]:
patron_Scifi=np.array([5, 1, 4])
patron_Comedia=np.array([1, 5, 3])

#### Matriz Asignal

In [5]:
A_signal=np.array([patron_Scifi, patron_Comedia, patron_Scifi*0.5+patron_Comedia*0.5, patron_Scifi*0.8+patron_Comedia*0.2])
print(f"Matriz A signal: {A_signal}")
print(f"Matriz A signal shape: {A_signal.shape}")

Matriz A signal: [[5.  1.  4. ]
 [1.  5.  3. ]
 [3.  3.  3.5]
 [4.2 1.8 3.8]]
Matriz A signal shape: (4, 3)


#### Señal de Ruido y Señal Real

In [6]:
np.random.seed(42)
ruido=np.random.randn(*A_signal.shape)*0.3
print(f"Ruido: {ruido}")

Ruido: [[ 0.14901425 -0.04147929  0.19430656]
 [ 0.45690896 -0.07024601 -0.07024109]
 [ 0.47376384  0.23023042 -0.14084232]
 [ 0.16276801 -0.13902531 -0.13971893]]


In [7]:
señal_real=A_signal+ruido
print(f"Señal real (A_signal + ruido): {señal_real}")

Señal real (A_signal + ruido): [[5.14901425 0.95852071 4.19430656]
 [1.45690896 4.92975399 2.92975891]
 [3.47376384 3.23023042 3.35915768]
 [4.36276801 1.66097469 3.66028107]]


#### Descomposición SVD de la Señal Real

In [8]:
U, S, VT = np.linalg.svd(señal_real)
print(f'Vector de valores singulares: {S}')

Vector de valores singulares: [11.49314153  4.10354919  0.27576758]


#### Filtración de Ruido con SVD con k=1

In [9]:
k=1

Sigma_k = np.diag(S[:k])
Sigma=np.diag(S)
print(f'Matriz Sigma_k con los {k} valores singulares más grandes: {Sigma_k}')
print(f'Matriz Sigma completa: {Sigma}')

Matriz Sigma_k con los 1 valores singulares más grandes: [[11.49314153]]
Matriz Sigma completa: [[11.49314153  0.          0.        ]
 [ 0.          4.10354919  0.        ]
 [ 0.          0.          0.27576758]]


In [10]:
U_k=U[:,:k]
VT_k=VT[:k,:]
print(f'Matriz U_k: {U_k}')
print(f'Matriz VT_k: {VT_k}')

Matriz U_k: [[-0.55286005]
 [-0.4308512 ]
 [-0.50160466]
 [-0.50705599]]
Matriz VT_k: [[-0.64638715 -0.44517193 -0.61968185]]


In [12]:
A_filtrada = U_k @ Sigma_k @ VT_k
print(f'Matriz A Signal: {A_signal}')
print(f'Matriz A filtrada: {np.round(A_filtrada, decimals=2)}')

Matriz A Signal: [[5.  1.  4. ]
 [1.  5.  3. ]
 [3.  3.  3.5]
 [4.2 1.8 3.8]]
Matriz A filtrada: [[4.11 2.83 3.94]
 [3.2  2.2  3.07]
 [3.73 2.57 3.57]
 [3.77 2.59 3.61]]


In [13]:
varianza_explicada_k = np.sum(S[:k]**2) / np.sum(S**2)
print(f'Varianza explicada por los {k} primeros componentes: {varianza_explicada_k:.2f}')

Varianza explicada por los 1 primeros componentes: 0.89


In [14]:
cociente_de_varianza_explicada_k = varianza_explicada_k / (1 - varianza_explicada_k)
print(f'Cociente de varianza explicada por los {k} primeros componentes: {cociente_de_varianza_explicada_k:.2f}')

Cociente de varianza explicada por los 1 primeros componentes: 7.81
